### ISSUE TITLE
Support just using fig to build and test?

### ISSUE THREAD

**Issue by ferrouswheel** [docker-systems/baleen#2]
Fig usually is used as a way to define an operational group of containers, but having a `fig_test.yml` and baleen passing that to fig might be a simple way to get something going in the short term.

**Comment by ferrouswheel** [comment]
See #4 for an implementation of this. Rather than add another .yml file, I opted to put what would be the contents of `fig.yml` in `baleen.yml`, under the `test` key. e.g

```yaml
test:
    # Unit tests generally run isolated from other containers.
    subject: # subject is always the container that is considered to run the tests.
      # The image will have a unique build tag added by baleen
      image: "docker.domarino.com/api"
      #links:
         # links to dependencies are auto added
         #- "db:db1" # remap the link, otherwise uses --link db. --link rabbitmq is implicit
      environment:
         TEST: 1
      command:
         - ./run_tests.sh
```
