### ISSUE TITLE
Automatically create container if artifacts exist from build process

### ISSUE THREAD

**Issue by ferrouswheel** [docker-systems/baleen#22]
Some CI tools use the build process in a dockerfile to run tests.

To make it simpler for people to use both, we should allow people to skip specifying the test section in a `baleen.yml`. e.g.

```
build:
    my.registry123124.com/PROJECTNAME: .

test:
    subject:
      image: "my.registry123124.com/PROJECTNAME"
      ## No need to run anything, the test results are already present from
      ## build, but we need a container in order to `docker cp` the results.
      command: "echo 1"

artifacts:
  xunit:
    path: /path/to/xunit
```

becomes:

```
build:
    my.registry123124.com/PROJECTNAME: .

artifacts:
  xunit:
    path: /path/to/xunit
```
